<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FutureCity.Headless</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FutureCity.Sim\FutureCity.Sim.csproj" />
    <ProjectReference Include="..\FutureCity.Content\FutureCity.Content.csproj" />
  </ItemGroup>

</Project>
